### ISSUE TITLE
Navigation Bar is broken on Daily view

### ISSUE THREAD

**Issue by franck-fourel** [coyotte508/blip#4]
Going to the daily view, we cannot navigate from day to day using the right and left arrow. It returns the following message:
```
Tidepool is stuck and isn't doing what you want it to do. We're sorry for the trouble.
Tidepool will attempt to send the details to our server.
UTC time: 2018-03-30T15:39:36.114Z
```
Same error in any language

**Comment by coyotte508** [comment]
I think it's fixed. I squished all changes in viz, tideline and blip into one commit for each repo, everything should be working fine.

**Comment by franck-fourel** [comment]
Sounds good now
