### ISSUE TITLE
Dexcom Banner

### ISSUE THREAD

**Issue by franck-fourel** [coyotte508/blip#9]
The donate section is hidden but Dexcom banner and section are still there
![dexcombanner](https://user-images.githubusercontent.com/22294614/38619225-fcca233e-3d9b-11e8-8eb3-fcbeeb360b4e.PNG)

**Comment by coyotte508** [comment]
I understand but it is different than the donate data banner, and is not justifiably removable for the same reasons. It is easy to remove but should I make another branch for it?

**Comment by franck-fourel** [comment]
I got it. can you please hide the dexcom banner with a new environment variable, only for Dexcom.

**Comment by coyotte508** [comment]
Done in https://github.com/coyotte508/blip/commit/b29d00154d53426b038ff613e7eaeb137a0eb4af
